modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }

[[module]]
name = "bazaar_ex"